// 1.hello-world/4.read-video-react/src/components/HelloWorld.js
import './HelloWorld.css';
import DBR from "../dbr";
import React from 'react';
import BarcodeScanner from './BarcodeScanner';

class HelloWorld extends React.Component {
    constructor(props) {
        super(props);
        this.refDivMessage = React.createRef();
        this.state = {
            libLoaded: false,
            resultValue: "",
            bShowScanner: false
        };
    }
    async componentDidMount() {
        await DBR.BarcodeScanner.loadWasm();
        this.setState(state => {
            state.libLoaded = true;
            return state;
        });
    }
    appendMessage = str => {
        this.setState(state => {
            state.resultValue = str;
            return state;
        });
    }
    showScanner = () => {
        this.setState({
            bShowScanner: true
        });
    }
    render() {
        return (
            <div class="helloWorld">
                <h1>Dynamsoft Barcode Reader Hello World Sample for React</h1>
                <button onClick={this.showScanner}>Start Barcode Scanner</button>
                <input type="text" value={this.state.resultValue} readonly="true" class="Input-text" placeholder="The Barcode Result" />
                <div id="scannerUI">
                    {!this.state.libLoaded ? (<span style={{ fontSize: "x-large" }}>Loading Library...</span>) : ""}
                    {this.state.bShowScanner ? (<BarcodeScanner appendMessage={this.appendMessage}></BarcodeScanner>) : ""}
                </div>
            </div>
        );
    }
}
export default HelloWorld;

// 1.hello-world/3. read-video-angular/src/app/hello-world/hello-world.component.ts
import { Component, OnInit } from '@angular/core';
import DBR from '../dbr';

@Component({
  selector: 'app-hello-world',
  templateUrl: './hello-world.component.html',
  styleUrls: ['./hello-world.component.css']
})
export class HelloWorldComponent implements OnInit {
  bShowScanner = false;
  resultValue = "";
  libLoaded = false;
  constructor() { }

  async ngOnInit(): Promise<void> {
    await DBR.BarcodeScanner.createInstance();
    this.libLoaded = true;
  }
  showScanner(): void {
    this.bShowScanner = true;
  }
  appendMessage(str: string) {
    console.log(str);
    this.resultValue = str;
  }
}

<div class="helloWorld">
  <h1>Dynamsoft Barcode Reader Hello World Sample for Angular</h1>
  <button (click)="showScanner()">Start Barcode Scanner</button>
  <input type="text" [value]="resultValue" readonly="true" class="Input-text" placeholder="The Barcode Result">
  <div id="scannerUI">
    <span style='font-size:x-large' *ngIf="!libLoaded">Loading Library...</span>
    <app-barcode-scanner *ngIf="bShowScanner" (appendMessage)="appendMessage($event)"></app-barcode-scanner>
  </div>
</div>
