// 1.hello-world/7.read-video-nextjs/components/ImgDecode.tsx
import React, { ChangeEvent, Component } from 'react'
import { BarcodeReader } from "dynamsoft-javascript-barcode";

export default class ImgDecode extends Component {
  pReader: Promise<BarcodeReader> = BarcodeReader.createInstance();

  decodeImg = async (e: ChangeEvent<HTMLInputElement>) => {
    try {
      const reader = await this.pReader;
      let results = await reader.decode(e.target.files![0]);
      for (let result of results) {
        alert(result.barcodeText);
      }
      if (!results.length) { alert('No barcode found'); }
    } catch (ex: any) {
      if (ex.message.indexOf("network connection error")) {
        let customMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
        console.log(customMsg);
        alert(customMsg);
      }
      throw ex;
    }
    e.target.value = '';
  }

  async componentWillUnmount() {
    if (this.pReader) {
      (await this.pReader).destroyContext();
      console.log('ImgDecode Component Unmount');
    }
  }

  render() {
    return (
      <div className="ImgDecode"><input type="file" onChange={this.decodeImg} /></div>
    )
  }
}

// 1.hello-world/6.read-video-vue3/src/components/ImgDecode.vue
<template>
  <div class="ImgDecode"><input type="file" @change="decodeImg" /></div>
</template>

<script>
import { onBeforeUnmount, ref } from "vue";
import { BarcodeReader } from 'dynamsoft-javascript-barcode'

export default {
  setup() {
    const pReader = ref(null);

    const decodeImg = async (e) => {
      try {
        const reader = await (pReader.value = pReader.value || BarcodeReader.createInstance());
        let results = await reader.decode(e.target.files[0]);
        for (let result of results) {
          alert(result.barcodeText);
        }
        if (!results.length) { alert('No barcode found'); }
      } catch (ex) {
        if (ex.message.indexOf("network connection error")) {
          let customMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
          console.log(customMsg);
          alert(customMsg);
        }
        throw ex;
      }
      e.target.value = '';
    }
    onBeforeUnmount(async () => {
      if (pReader.value) {
        (await pReader.value).destroyContext();
        console.log('ImgDecode Component Unmount');
      }
    })

    return {
      decodeImg
    }
  }
}
</script>

<style scoped>
.ImgDecode {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 90%;
  border: 1px solid black
}
</style>
