// 1.hello-world/read-video-react-hook/src/components/ImgDecode/ImgDecode.tsx
import React, { useState, useEffect } from "react";
import { BarcodeReader } from "dynamsoft-javascript-barcode";
import "./ImgDecode.css";

function ImgDecode() {
  let [pReader, setPReader] = useState(null as any);

  const decodeImg = async (e: React.ChangeEvent<HTMLInputElement>) => {
    try {
      const reader: BarcodeReader = await pReader;
      let results = await reader.decode(e.target.files![0]);
      for (let result of results) {
        alert(result.barcodeText);
      }
      if (!results.length) {
        alert("No barcode found");
      }
    } catch (ex: any) {
      if (ex.message.indexOf("network connection error")) {
        let customMsg =
          "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
        console.log(customMsg);
        alert(customMsg);
      }
      throw ex;
    }
    e.target.value = "";
  };

  useEffect(() => {
    setPReader((pReader = BarcodeReader.createInstance()));
    return () => {
      (async () => {
        if (pReader) {
          (await pReader).destroyContext();
          console.log("ImgDecode Component Unmount");
        }
      })();
    };
  }, []);

  return (
    <div className="ImgDecode">
      <input type="file" onChange={decodeImg} />
    </div>
  );
}

export default ImgDecode;

// 1.hello-world/5.read-video-vue/src/components/ImgDecode.vue
<template>
  <div class="ImgDecode"><input type="file" @change="decodeImg" /></div>
</template>

<script>
import { BarcodeReader } from 'dynamsoft-javascript-barcode'
export default {
  name: 'ImgDecode',
  data() {
    return {
      pReader: null,
    }
  },
  methods: {
    async decodeImg(e) {
      try {
        const reader = await (this.pReader = this.pReader || BarcodeReader.createInstance());
        let results = await reader.decode(e.target.files[0]);
        for (let result of results) {
          alert(result.barcodeText);
        }
        if (!results.length) { alert('No barcode found'); }
      } catch (ex) {
        if (ex.message.indexOf("network connection error")) {
          let customMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
          console.log(customMsg);
          alert(customMsg);
        }
        throw ex;
      }
      e.target.value = '';
    }
  },
  async beforeDestroy() {
    if (this.pReader) {
      (await this.pReader).destroyContext();
      console.log('ImgDecode Component Unmount');
    }
  },
}
</script>

<style scoped>
.ImgDecode {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 90%;
  border: 1px solid black
}
</style>
