// hello-world/next/components/HelloWorld/HelloWorld.tsx
"use client"

import React, { useState } from "react";
import "../../dbr"; // import side effects. The license, engineResourcePath, so on.
import "../../cvr"; // import side effects. The license, engineResourcePath, so on.
import "../../dce"; // import side effects. The license, engineResourcePath, so on.
import VideoCapture from "../VideoCapture/VideoCapture";
import ImageCapture from "../ImageCapture/ImageCapture";
import "./HelloWorld.css";

function HelloWorld() {
  let [bShowVideoCapture, setBShowVideoCapture] = useState(true);
  let [bShowImageCapture, setBShowImageCapture] = useState(false);

  const showVideoCapture = () => {
    setBShowVideoCapture(true);
    setBShowImageCapture(false);
  };

  const showImageCapture = () => {
    setBShowVideoCapture(false);
    setBShowImageCapture(true);
  };

  return (
    <div className="div-hello-world">
      <h1>Hello World for React(Hooks)</h1>
      <div>
        <button
          style={{
            marginRight: "10px",
            backgroundColor: bShowVideoCapture ? "rgb(255,174,55)" : "white",
          }}
          onClick={showVideoCapture}
        >
          Decode Video
        </button>
        <button
          style={{
            backgroundColor: bShowImageCapture ? "rgb(255,174,55)" : "white",
          }}
          onClick={showImageCapture}
        >
          Decode Image
        </button>
      </div>
      <div className="container">
        {bShowVideoCapture ? <VideoCapture></VideoCapture> : ""}
        {bShowImageCapture ? <ImageCapture></ImageCapture> : ""}
      </div>
    </div>
  );
}

export default HelloWorld;

// hello-world/angular/src/app/hello-world/hello-world.component.ts
import { Component } from '@angular/core';
// import '../dbr'; // import side effects. The license, engineResourcePath, so on.
// import '../../cvr'; // import side effects. The license, engineResourcePath, so on.
// import '../dce'; // import side effects. The license, engineResourcePath, so on.
import '../../dbr'; // import side effects. The license, engineResourcePath, so on.
import '../../cvr'; // import side effects. The license, engineResourcePath, so on.
import '../../dce'; // import side effects. The license, engineResourcePath, so on.

@Component({
  selector: 'app-hello-world',
  templateUrl: './hello-world.component.html',
  styleUrls: ['./hello-world.component.css']
})
export class HelloWorldComponent {
  bShowVideoCapture = true;
  bShowImageCapture = false;
  
  showVideoCapture(): void {
    this.bShowVideoCapture = true;
    this.bShowImageCapture = false;
  }
  showImageCapture(): void {
    this.bShowVideoCapture = false;
    this.bShowImageCapture = true;
  }
}

<div class="div-hello-world">
  <h1>Hello World for Angular</h1>
  <div>
      <button [ngStyle]="{'margin-right': '10px', 'background-color': bShowVideoCapture ? 'rgb(255,174,55)' : 'white'}" (click)="showVideoCapture()">Decode Video</button>
      <button [ngStyle]="{'background-color': !bShowVideoCapture ? 'rgb(255,174,55)' : 'white'}" (click)="showImageCapture()">Decode Image</button>
  </div>
  <div class="container">
      <app-video-capture *ngIf="bShowVideoCapture"></app-video-capture>
      <app-image-capture *ngIf="bShowImageCapture"></app-image-capture>
  </div>
</div>
