// hello-world/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'my-app';

  mode: string = "video";

  switchMode(value: string) {
    this.mode = value;
  }
}

<div class='App'>
  <div class='title'>
    <h2 class='title-text'>Hello World for Angular</h2>
    <img class='title-logo' src="./assets/logo.svg" alt="logo" />
  </div>
  <div class='top-btns'>
    <button (click)="switchMode('video')" [ngStyle]="{'background-color': mode === 'video' ? 'rgb(255,174,55)' : 'white'}">Video Capture</button>
    <button (click)="switchMode('image')" [ngStyle]="{'background-color': mode === 'image' ? 'rgb(255,174,55)' : 'white'}">Image Capture</button>
  </div>
  <app-video-capture *ngIf="mode === 'video'"></app-video-capture>
  <app-image-capture *ngIf="mode === 'image'"></app-image-capture>
</div>

// hello-world/react-hooks/src/App.tsx
import { useState } from 'react';
import './App.css';
import reactLogo from './assets/logo.svg';
import VideoCapture from './components/VideoCapture/VideoCapture';
import ImageCapture from './components/ImageCapture/ImageCapture';

function App() {
  const [mode, setMode] = useState("video");
  return (
    <div className='App'>
      <div className='title'>
        <h2 className='title-text'>Hello World for React</h2>
        <img className='title-logo' src={reactLogo} alt="logo"></img>
      </div>
      <div className='top-btns'>
        <button onClick={()=>{setMode("video")}} style={{backgroundColor: mode === "video" ? "rgb(255, 174, 55)" : "#fff"}}>Video Capture</button>
        <button onClick={()=>{setMode("image")}} style={{backgroundColor: mode === "image" ? "rgb(255, 174, 55)" : "#fff"}}>Image Capture</button>
      </div>
      { mode === "video" ? <VideoCapture /> : <ImageCapture /> }
    </div>
  );
}

export default App;
